import { systemRouter } from "./_core/systemRouter";
import { router } from "./_core/trpc";
import {
  authRouter,
  profileRouter,
  usersRouter,
  dailyLogRouter,
  measurementsRouter,
  mealPlanRouter,
  shoppingRouter,
  macroTargetRouter,
  trainingRouter,
  mesoRouter,
  workoutSessionsRouter,
  exerciseLibraryRouter,
  equipmentPresetsRouter,
  checkInRouter,
  habitsRouter,
  timelineRouter,
  notesRouter,
  nutritionFoodsRouter,
  onboardingRouter,
  clientConfigRouter,
  changeLogRouter,
  progressRouter,
  progressPhotosRouter,
  questionsRouter,
  phasesRouter,
  invitesRouter,
} from "./routers/index";

export const appRouter = router({
  system: systemRouter,
  auth: authRouter,
  profile: profileRouter,
  users: usersRouter,
  dailyLog: dailyLogRouter,
  measurements: measurementsRouter,
  mealPlan: mealPlanRouter,
  shopping: shoppingRouter,
  macroTarget: macroTargetRouter,
  training: trainingRouter,
  meso: mesoRouter,
  workoutSessions: workoutSessionsRouter,
  exerciseLibrary: exerciseLibraryRouter,
  equipmentPresets: equipmentPresetsRouter,
  checkIn: checkInRouter,
  habits: habitsRouter,
  timeline: timelineRouter,
  notes: notesRouter,
  nutritionFoods: nutritionFoodsRouter,
  onboarding: onboardingRouter,
  clientConfig: clientConfigRouter,
  changeLog: changeLogRouter,
  progress: progressRouter,
  progressPhotos: progressPhotosRouter,
  questions: questionsRouter,
  phases: phasesRouter,
  invites: invitesRouter,
});

export type AppRouter = typeof appRouter;
