#!/usr/bin/env python3
"""
AFCD Food Database Cleanup Script

Strategy:
1. Keep only the most useful entry per food (prefer raw for whole foods;
   for meats keep raw + one cooked method where macros differ meaningfully)
2. Consolidate varieties into single entries (all apple varieties → one apple)
3. Remove entries unlikely to be used in coaching meal plans
4. Simplify verbose names into readable sentence-case format
5. Re-insert cleaned data, then re-run serving sizes

The script reads the current nutrition_foods table, applies cleanup rules,
deletes all rows, and re-inserts the cleaned set.
"""

import mysql.connector
import re

DB_PARAMS = {
    'user': '3K2x4Mgy2RpvvVT.root',
    'password': 'Ta3euAH93De7dGlu54yl',
    'host': 'gateway05.us-east-1.prod.aws.tidbcloud.com',
    'port': 4000,
    'database': 'HZf6zqYa94nKHY3YxXLHa5',
    'ssl_disabled': False,
}

# ─────────────────────────────────────────────────────────────────────────────
# STEP 1: Define which entries to REMOVE entirely
# ─────────────────────────────────────────────────────────────────────────────

# Exact names to remove
REMOVE_EXACT = {
    # Water
    'Water, bottled, still',
    'Water, soda',
    'Water, tap',
    'Water, coconut, commercial',  # keep Coconut water separately if needed
    # Human milk
    'Milk, human/breast, mature, fluid',
    # Highly processed/unlikely coaching foods
    'Spam, regular fat',
    'Braised steak & onions, canned',
    'Spaghetti in tomato & cheese sauce, canned',
    'Sausages & vegetables, canned',
    'Steak & vegetables, canned',
    'Chicken piece, flesh, skin & fat, coated, fast food outlet, fried',
    'Chicken, nugget, purchased from fast food chain, grilled',
    'Chicken, nugget, purchased from independent takeaway & fast food chain, fried, undefined oil',
    'Chicken, barbecued, with skin',
    # Separable fat entries (not useful for meal planning)
    'Beef, all cuts, separable fat, cooked, no added fat',
    'Beef, all cuts, separable fat, raw',
    'Chicken, separable fat, composite, baked or roasted, no added fat',
    'Chicken, separable fat, composite, cooked, no added fat',
    'Chicken, separable fat, composite, raw',
    'Chicken, skin, composite, baked, no added fat',
    'Chicken, skin, composite, casseroled, no added fat',
    'Chicken, skin, composite, raw',
    'Lamb, all cuts, separable fat, cooked',
    'Lamb, all cuts, separable fat, raw',
    'Pork, forequarter (chop, roast, neck), separable fat, raw',
    'Pork, forequarter, separable fat, BBQ\'d, no added fat',
    'Pork, leg steak (rump), separable fat, fried, no added fat',
    'Pork, leg steak (rump), separable fat, raw',
    'Pork, loin chop, separable fat, BBQ\'d, no added fat',
    'Pork, loin chop, separable fat, raw',
    'Pork, medallion or loin steak, separable fat, fried, no added fat',
    'Pork, medallion or loin steak, separable fat, raw',
    'Pork, rump steak, separable fat, fried, no added fat',
    'Pork, rump steak, separable fat, raw',
    'Veal, all cuts, separable fat, cooked',
    'Veal, all cuts, separable fat, raw',
    # Obscure/exotic items unlikely in Australian coaching context
    'Camel, mince, raw',
    'Buffalo, mince, raw',
    'Quail, whole, lean flesh, raw',
    'Rabbit, lean flesh, raw',
    'Duck, breast, lean flesh, raw',
    'Duck, breast, lean flesh, skin & fat, raw',
    'Wax jambu, raw',
    'Quandong, raw',
    'Prickly pear, raw',
    'Rambutan, raw',
    'Wattle seed (acacia), ground',
    'Vine leaf, grape, canned',
    'Tamarillo, raw',
    'Tamarind, raw',
    'Guava, raw',
    'Lime, native, fruit',
    'Yam, wild harvested, cooked',
    'Kangaroo, tail, cooked, no added fat',
    'Kangaroo, tail, raw',
    # Cooking ingredients unlikely to be tracked
    'Baking powder, dry powder',
    'Baking soda (bicarbonate), dry powder',
    'Cream of tartar, dry powder',
    'Vanilla, artificial or imitation',
    'Vanilla bean extract',
    'Yeast, dry powder',
    'Inulin, dry powder',
    'Starch, corn (cornflour)',
    'Starch, potato',
    'Salt, table',
    'Salt substitute',
    'Taco seasoning mix, dry',
    'Mustard powder',
    # Canned/processed soups
    'Soup, chicken & noodle, cup of soup, prepared from instant dry mix with water',
    'Soup, tomato, canned, condensed, prepared with water',
    # Misc unlikely
    'Psyllium, husks',
    'Seaweed, dried',
    'Bamboo shoot, canned in water, heated, drained',
    'Water chestnut, peeled, canned, drained',
    'Vine leaf, grape, canned',
    'Potato straws, commercial, salted',
    'Vegetable crisps or chips, sweet potato & taro, flavoured',
    'Snack ball, bliss ball, nut & date based',
    'Tart, custard, commercial',
    'Pudding, bread & butter, homemade',
    'Cake mix, chocolate, dry',
    'Cake or cupcake, chocolate, commercial',
    'Cake, carrot, commercial',
    'Cake, chocolate, homemade',
    'Cake, fruit, commercial',
    'Cake, sponge, plain, homemade',
    'Slice, caramel, commercial',
    'Slice, chocolate, commercial',
    'Pie, savoury, chicken & vegetable, commercial',
    'Pie, savoury, meat, commercial',
    'Sausage roll, commercial, baked',
    'Spring roll, commercial, baked',
    'Caramels',
    'Triticale, grain, uncooked',
    'Sago, uncooked',
    'Tapioca, pearl or seed style, boiled, no added fat or salt',
    'Tapioca, pearl or seed style, uncooked',
    'Rhubarb, raw',
    'Quince, raw',
    'Choko, peeled, boiled, drained',
    'Choko, peeled, raw',
    'Chicory or endive, raw',
    'Celeriac, peeled, fresh, raw',
    'Artichoke, jerusalem, peeled, boiled, drained',
    'Artichoke, jerusalem, peeled, raw',
    'Artichoke, globe, boiled, drained',
    'Artichoke, globe, raw',
    'Artichoke heart, canned in brine, drained',
    'Fennel bulb, raw',
    'Leek, fresh, boiled, drained',
    'Swede, peeled, fresh, boiled, drained',
    'Swede, peeled, fresh, raw',
    'Turnip, white, peeled, fresh, boiled, no added fat',
    'Turnip, white, peeled, fresh, raw',
    'Radish, red, raw',
    'Watercress, raw',
    'Sprout, alfalfa, raw',
    'Sprout, broccoli, raw',
    'Squash, button, raw',
    'Lemon peel, raw',
    'Lemon, preserved',
    'Capers, canned in brine, drained',
    'Chutney or relish, fruit based',
    'Dip, tzatziki, commercial',
    'Stock, beef, liquid, commercial',
    'Stock, chicken, liquid, commercial',
    'Stock, vegetable, liquid, commercial',
    'Sauce, butter chicken, commercial',
    'Sauce, simmer for chicken, commercial',
    'Sauce, hoisin, commercial',
    'Beverage base, chocolate flavoured, dry powder',
    'Beverage, chocolate flavoured, prepared with cow\'s milk, reduced fat',
    'Beverage, coffee flavoured, prepared with cow\'s milk, regular fat',
    'Beverage, coffee flavoured, prepared with cow\'s milk, reduced fat',
    'Beverage, flavoured milk, prepared with cow\'s milk, reduced fat',
    'Alcoholic beverage, spirit, ~30% v/v, all (Brandy, Gin, Rum, Vodka and Whisky), cooked',
    'Wine, red, cooked',
    'Wine, white, cooked',
    'Cider, alcoholic, ~4.5% v/v',
    'Beer, non-alcoholic, <0.5% v/v',
    'Soft drink, cola type, diet or zero sugar',
    'Soft drink, fruit flavoured, diet or zero sugar',
    'Soft drink, lemonade, regular',
    'Soft drink, fruit flavoured, regular',
    'Tea, black, brewed from leaf or teabags, decaffeinated',
    'Coffee, flat white, regular fat cow\'s milk',
    'Coffee, latte, regular fat cow\'s milk',
    'Coffee, skim flat white',
    'Coffee, skim latte',
    'Coffee, long black (americano), no milk or sugar',
    'Banana chip',
    'Rice paper wrapper, soaked in water',
    'Noodle, buckwheat (soba), boiled, no added fat',
    'Noodle, rice, boiled, no added fat',
    'Noodle, rice, dry',
    'Noodle, wheat with egg, plain, boiled, no added fat',
    'Noodle, wheat, plain, boiled, no added fat',
    'Noodle, wheat, plain, dry',
    'Bread, pizza base, commercial',
    'Bread, garlic or herb, homemade, cooked',
    'Bread, garlic, commercial, baked',
    'Bread, damper, from white flour, homemade',
    'Bread, damper, homemade, toasted',
    'Bread, banana, commercial',
    'Bread, banana, homemade',
    'Bread, brioche',
    'Bread, organic',
    'Bread, organic, toasted',
    'Scone, plain, homemade',
    'Teff, uncooked',
    'Spelt, grain, uncooked',
    'Sorghum, grain, uncooked',
    'Rye, grain, uncooked',
    'Amaranth, grain, whole, uncooked',
    'Triticale, grain, uncooked',
    'Buckwheat groats, uncooked',
    'Wheat, whole, uncooked',
    'Semolina, uncooked',
    'Psyllium, husks',
    'Textured vegetable protein/soy granules',
    'Tempeh, plain',
    'Bean sprout, mung, canned, drained',
    'Bean sprout, soy, raw',
    'Edamame, frozen, boiled, drained',
    'Chickpea, dried',
    'Lentil, French, hulled, dry',
    'Lentil, green, hulled, dry',
    'Lentil, hulled, dry',
    'Lentil, red, hulled, dry',
    'Bean, adzuki, dried, boiled, drained',
    'Bean, black, dried, boiled, drained',
    'Bean, lima, dried, boiled, drained',
    'Bean, mung, dried, boiled, drained',
    'Bean, navy, dried, boiled, drained',
    'Bean, pinto, dried, boiled, drained',
    'Bean, soy, dried, boiled, drained',
    'Bean, soy, canned, drained',
    'Pea, split, yellow, dried, boiled, drained',
    'Pea, split, yellow, dried, uncooked',
    'Parsley, fresh, raw',
    'Rosemary, fresh, raw',
    'Thyme, dried, ground',
    'Thyme, fresh, raw',
    'Sage, dried, ground',
    'Coriander (cilantro), fresh, raw',
    'Basil, green, fresh, raw',
    'Chives, fresh, raw',
    'Cardamom seed, dried, ground',
    'Cloves, dried, ground',
    'Fenugreek seed, dried',
    'Cinnamon, dried, ground',
    'Cumin (cummin) seed, dried, ground',
    'Coriander seed, dried, ground',
    'Turmeric, dried, ground',
    'Ginger, dried, ground',
    'Chilli (chili), dried, ground',
    'Treacle or molasses',
    'Syrup, golden',
    'Sugar, brown',
    'Sugar, raw (turbinado)',
    'Sugar, white',
    'Sultana',
    'Raisin',
    'Prune (dried plum)',
    'Date, raw',
    'Fig, dried',
    'Apricot, dried',
    'Apple, dried',
    'Cocoa powder, plain',
    'Chocolate, white',
    'Bar, cherry & coconut centre, dark chocolate-coated',
    'Bar, coconut cream centre, milk chocolate-coated',
    'Bar, honeycomb centre, milk chocolate-coated',
    'Bar, nougat & caramel centre, milk chocolate-coated',
    'Bar, wafer & cream layers, chocolate-coated',
    'Biscuit, chocolate, cream filled',
    'Biscuit, chocolate, plain',
    'Biscuit, crispbread, rye, plain',
    'Biscuit, crispbread, rye, seeded',
    'Biscuit, crispbread, wheat, plain',
    'Biscuit, gingernut',
    'Biscuit, oatmeal',
    'Biscuit, plain sweet',
    'Biscuit, shortbread',
    'Biscuit, wafer, cream filled',
    'Crumpet, commercial',
    'Bagel, from white flour, commercial, toasted',
    'Corn thins',
    'Taco shell, corn, commercial',
    'Couscous, uncooked',
    'Bulgur (burghul), uncooked',
    'Barley, pearl, uncooked',
    'Rice, wild, boiled, no added salt',
    'Rice, wild, uncooked',
    'Rice, white, fried with bacon or ham, egg, prawns & vegetables',
    'Rice, white, purchased as \'instant\', microwaved',
    'Pasta, gluten free, boiled from dry, no added salt',
    'Pasta, legume based, boiled, no added salt',
    'Pasta, white wheat flour & egg, dry',
    'Pasta, white wheat flour & spinach, boiled from dry, no added salt',
    'Pasta, white wheat flour & spinach, dry',
    'Pasta, white wheat flour, fresh, boiled, no added salt',
    'Pasta, white wheat flour, fresh, uncooked',
    'Pasta, wholemeal wheat flour, dry',
    'Bread, from white flour, added fibre, toasted',
    'Bread, from white flour, added omega-3 polyunsaturates, toasted',
    'Bread, from white flour, commercial, added dried fruit',
    'Bread, from white flour, Italian-style, commercial, toasted',
    'Bread, from white flour, sour dough, toasted',
    'Bread, from white flour, Turkish, toasted',
    'Bread, from white Jackaroo flour, added fibre and vitamins B1 & folate & Fe',
    'Bread, from white Jackaroo flour, added fibre and vitamins B1 & folate & Fe, toasted',
    'Bread, from white wheat flour, added dried fruit, toasted',
    'Bread, from wholemeal flour, toasted',
    'Bread, gluten free, toasted',
    'Bread, mixed grain, toasted',
    'Bread, from rye flour, sour dough, toasted',
    'Breakfast cereal, oat porridge, cooked with water',
    'Breakfast cereal, muesli, toasted',
    'Oats, rolled, mixed with sugar or honey & other flavours, uncooked',
    'Milk, cow, canned, sweetened, condensed, regular',
    'Milk, cow, fluid, flavoured, chocolate, reduced fat',
    'Milk, cow, fluid, prepared from dry powder, regular fat, standard dilution',
    'Milk, cow, fluid, prepared from dry powder, skim, standard dilution',
    'Milk, cow, powder, regular fat',
    'Milk, cow, powder, regular fat, added vitamins A & D',
    'Milk, cow, powder, regular fat, unfortified',
    'Milk, cow, powder, skim',
    'Yoghurt, natural, sheep\'s milk',
    'Yoghurt, soy based, berry flavoured, regular fat (~3%)',
    'Yoghurt, soy based, vanilla flavoured, reduced fat (~1%)',
    'Yoghurt, almond based, flavoured',
    'Yoghurt, coconut based, flavoured',
    'Cheese, hard, dairy alternative',
    'Cheese, cheddar, processed, reduced fat (~15%), added vitamin D',
    'Cheese, cheddar, processed, regular fat',
    'Cheese, goat, firm',
    'Cheese, goat, soft',
    'Cheese, edam',
    'Cheese, brie',
    'Cheese, camembert',
    'Cheese, blue vein',
    'Cream, imitation (non-dairy)',
    'Abalone, black lip, aquacultured, raw',
    'Abalone, black lip, wild, raw',
    'Abalone, brown lip, wild, raw',
    'Abalone, green lip, aquacultured, raw',
    'Abalone, green lip, wild, raw',
    'Shark, gummy, fillet, baked, no added fat',
    'Shark, gummy, fillet, raw',
    'Silver perch, fillet, baked, no added fat',
    'Silver perch, fillet, raw',
    'Sprat, whole, fried, no added fat',
    'Sprat, whole, raw',
    'Tilapia, fillet, baked, no added fat',
    'Tilapia, fillet, steamed, no added fat',
    'Bream, fillet, baked, no added fat',
    'Bream, fillet, steamed, no added fat',
    'Flathead, fillet, baked, no added fat',
    'Flathead, fillet, steamed, no added fat',
    'Blue grenadier (hoki), fillet, baked, no added fat',
    'Blue grenadier (hoki), fillet, steamed, no added fat',
    'Bassa (basa), fillet, baked, no added fat',
    'Bassa (basa), fillet, steamed, no added fat',
    'Barramundi, aquacultured, fillet, steamed with no added fat',
    'Snapper, fillet, baked, no added fat',
    'Snapper, fillet, steamed, no added fat',
    'Whiting, King George, fillet, baked, no added fat',
    'Whiting, King George, fillet, steamed, no added fat',
    'Trout, ocean, aquacultured, fillet, without skin, baked, no added fat',
    'Trout, ocean, aquacultured, fillet, without skin, steamed, no added fat',
    'Trout, rainbow, aquacultured, baked, no added fat',
    'Trout, rainbow, aquacultured, steamed, no added fat',
    'Salmon, Atlantic, fillet, steamed, no added fat',
    'Salmon, Pacific King, fillet, steamed, no added fat',
    'Salmon, flavoured, canned',
    'Tuna, flavoured, canned in oil',
    'Tuna, canned in brine, drained',
    'Sardine, Australian, whole, fried, no added fat',
    'Anchovy, canned in oil, drained',
    'Crab, flesh, purchased steamed or boiled',
    'Lobster, southern rock, wild, flesh, raw',
    'Lobster or crayfish, flesh, purchased steamed, poached or boiled, no added fat',
    'Mussel, blue, steamed',
    'Scallop, commercial, steamed',
    'Octopus, boiled, no added fat',
    'Squid or calamari, raw',
    'Prawn, banana, aquacultured, purchased cooked',
    'Prawn, banana, wild, flesh, raw',
    'Prawn, black tiger, aquacultured, purchased cooked',
    'Prawn, brown tiger, wild, flesh, raw',
    'Prawn, endeavour, wild, flesh, raw',
    'Prawn, school, wild, flesh, raw',
    'Prawn, Western king, wild, flesh, raw',
    'Sweetcorn, canned in water, drained',
    'Tomato, whole, canned in tomato juice, no added salt, undrained',
    'Tomato, whole, canned in tomato juice, undrained',
    'Tomato, paste, no added salt',
    'Tomato, sundried',
    'Tomato, puree, commercial',
    'Pineapple, canned in pineapple juice',
    'Pineapple, canned in pineapple juice, juice only',
    'Pineapple, canned in syrup',
    'Pineapple, canned in syrup, drained',
    'Pineapple, canned in syrup, syrup only',
    'Pineapple, peeled, frozen',
    'Peach, canned in pear juice',
    'Peach, canned in pear juice, drained',
    'Peach, canned in pear juice, juice only',
    'Pear, canned in pear juice',
    'Pear, canned in pear juice, drained',
    'Pear, canned in pear juice, juice only',
    'Apricot, canned in pear juice',
    'Apricot, canned in pear juice, drained',
    'Apricot, canned in pear juice, juice only',
    'Cherry, sour, canned in syrup',
    'Cherry, sour, canned in syrup, drained',
    'Cherry, sour, canned in syrup, syrup only',
    'Strawberry, canned in syrup',
    'Strawberry, canned in syrup, drained',
    'Strawberry, canned in syrup, syrup only',
    'Mango, pulped, canned',
    'Grape, black muscatel (muscat), raw',
    'Grape, black sultana, raw',
    'Grape, cornichon, raw',
    'Grape, waltham cross, raw',
    'Grapefruit, pink flesh, peeled, raw',
    'Grapefruit, yellow flesh, peeled, raw',
    'Lychee, raw',
    'Pomegranate, raw',
    'Papaya (pawpaw), raw',
    'Rockmelon (cantaloupe), peeled, raw',
    'Honeydew melon, peeled, raw',
    'Tangelo, peeled, raw',
    'Tangerine or tangor, peeled, raw',
    'Nectarine, raw',
    'Fig, raw',
    'Plum, raw',
    'Date, medjool, raw',
    'Coconut, shredded, sweetened',
    'Coconut, desiccated, unsweetened',
    'Coconut, flesh, fresh, raw',
    'Maple syrup',
    'Honey, commercial blend',
    'Jam or jelly, fruit, commercial',
    'Margarine, polyunsaturated fat, regular',
    'Margarine, polyunsaturated fat, reduced fat',
    'Ghee, cow\'s milk',
    'Oil, almond',
    'Oil, linseed or flaxseed',
    'Oil, macadamia',
    'Oil, palm',
    'Oil, peanut',
    'Oil, rice bran',
    'Oil, sesame',
    'Oil, vegetable blend',
    'Vinegar (except balsamic vinegar)',
    'Vinegar, balsamic',
    'Sauce, barbecue, commercial',
    'Sauce, fish, commercial',
    'Sauce, worcestershire, commercial',
    'Sauce, tomato (ketchup), commercial',
    'Dip, avocado (guacamole), commercial',
    'Dip, hummus (hommus), commercial',
    'Mayonnaise, regular fat',
    'Mayonnaise, reduced fat',
    'Pork, crackling, roasted, salted',
    'Pork, diced, untrimmed, fried, no added fat',
    'Pork, diced, untrimmed, raw',
    'Pork, strips, untrimmed, fried, no added fat',
    'Pork, strips, untrimmed, raw',
    'Pork, loin cutlet, untrimmed, fried, no added fat',
    'Pork, loin cutlet, untrimmed, raw',
    'Pork, rump steak, untrimmed, fried, no added fat',
    'Pork, rump steak, untrimmed, raw',
    'Pork, medallion or loin steak, untrimmed, fried, no added fat',
    'Pork, medallion or loin steak, untrimmed, raw',
    'Pork, butterfly steak, untrimmed, grilled, no added fat',
    'Pork, butterfly steak, untrimmed, raw',
    'Pork, forequarter chop, untrimmed, BBQ\'d, no added fat',
    'Pork, forequarter chop, untrimmed, raw',
    'Pork, loin chop, untrimmed, BBQ\'d, no added fat',
    'Pork, loin chop, untrimmed, raw',
    'Pork, belly, rind removed, baked, no added fat',
    'Lamb, chop, with bone, forequarter, lean, grilled, no added fat',
    'Lamb, chop, with bone, forequarter, lean, raw',
    'Lamb, chop, with bone, forequarter, untrimmed, raw',
    'Lamb, chop, with bone, forequarter, grilled, no added fat',
    'Lamb, chop, with bone, chump, lean, grilled, no added fat',
    'Lamb, chop, with bone, chump, lean, raw',
    'Lamb, chop, with bone, chump, untrimmed, grilled, no added fat',
    'Lamb, chop, with bone, chump, untrimmed, raw',
    'Lamb, cutlet or frenched cutlet, with bone, untrimmed, grilled, no added fat',
    'Lamb, cutlet or frenched cutlet, with bone, untrimmed, raw',
    'Lamb, diced, untrimmed, casseroled, no added fat',
    'Lamb, diced, untrimmed, raw',
    'Lamb, diced, untrimmed, stir-fried, no added fat',
    'Lamb, leg, untrimmed, baked, no added fat',
    'Lamb, leg, untrimmed, raw',
    'Lamb, loin chop, untrimmed, grilled, no added fat',
    'Lamb, loin chop, untrimmed, raw',
    'Lamb, rack, untrimmed, baked, no added fat',
    'Lamb, rack, untrimmed, raw',
    'Lamb, shoulder, untrimmed, baked, no added fat',
    'Lamb, shoulder, untrimmed, raw',
    'Lamb, strips, untrimmed, stir-fried, no added fat',
    'Lamb, mince, regular fat, raw',
    'Lamb, mince, regular fat, stir-fried, no added fat',
    'Beef, casserole meat, boneless or bone-in, shin, lean, casseroled, no added fat',
    'Beef, casserole meat, boneless or bone-in, shin, lean, raw',
    'Beef, casserole meat, boneless or bone-in, shin, untrimmed, casseroled, no added fat',
    'Beef, casserole meat, boneless or bone-in, shin, untrimmed, raw',
    'Beef, casserole meat, boneless, chuck, lean, casseroled, no added fat',
    'Beef, casserole meat, boneless, chuck, lean, raw',
    'Beef, casserole meat, boneless, chuck, untrimmed, casseroled, no added fat',
    'Beef, casserole meat, boneless, chuck, untrimmed, raw',
    'Beef, diced, untrimmed, casseroled, no added fat',
    'Beef, diced, untrimmed, dry-fried, no added fat',
    'Beef, diced, untrimmed, raw',
    'Beef, mince, higher fat, raw',
    'Beef, mince, higher fat, stir-fried, no added fat',
    'Beef, mince, regular fat, raw',
    'Beef, mince, regular fat, stir-fried, no added fat',
    'Beef, rump steak, untrimmed, BBQ\'d, no added fat',
    'Beef, rump steak, untrimmed, raw',
    'Beef, scotch fillet (rib eye), untrimmed, BBQ\'d, no added fat',
    'Beef, scotch fillet (rib eye), untrimmed, raw',
    'Beef, sirloin (porterhouse), untrimmed, BBQ\'d, no added fat',
    'Beef, sirloin (porterhouse), untrimmed, raw',
    'Beef, stir-fry strips, untrimmed, dry-fried, no added fat',
    'Beef, stir-fry strips, untrimmed, raw',
    'Beef, strips, lean, casseroled, no added fat',
    'Beef, strips, untrimmed, casseroled, no added fat',
    'Beef, T-bone steak, untrimmed, BBQ\'d, no added fat',
    'Beef, T-bone steak, untrimmed, raw',
    'Beef, tenderloin (eye fillet), untrimmed, BBQ\'d, no added fat',
    'Beef, tenderloin (eye fillet), untrimmed, raw',
    'Beef, topside steak, untrimmed, BBQ\'d, no added fat',
    'Beef, topside steak, untrimmed, raw',
    'Veal, cutlet, with bone, untrimmed, grilled, no added fat',
    'Veal, cutlet, with bone, untrimmed, raw',
    'Veal, diced, untrimmed, raw',
    'Veal, diced, untrimmed, stir-fried, no added fat',
    'Veal, steak, boneless, leg, untrimmed, grilled, no added fat',
    'Veal, steak, boneless, leg, untrimmed, raw',
    'Veal, stir-fry strips, untrimmed, raw',
    'Veal, stir-fry strips, untrimmed, stir-fried, no added fat',
    'Chicken, breast, lean flesh, skin & fat, baked, no added fat',
    'Chicken, breast, lean flesh, skin & fat, raw',
    'Chicken, drumstick, lean flesh, skin & fat, baked, no added fat',
    'Chicken, drumstick, lean flesh, skin & fat, casseroled, no added fat',
    'Chicken, drumstick, lean flesh, skin & fat, raw',
    'Chicken, thigh, lean flesh, skin & fat, baked, no added fat',
    'Chicken, thigh, lean flesh, skin & fat, casseroled, no added fat',
    'Chicken, thigh, lean flesh, skin & fat, raw',
    'Chicken, wing, lean flesh, skin & fat, baked, no added fat',
    'Chicken, wing, lean flesh, skin & fat, baked, no added fat',
    'Chicken, wing, lean flesh, skin & fat, casseroled, no added fat',
    'Chicken, wing, lean flesh, skin & fat, raw',
    'Turkey, breast, lean flesh, skin & fat, baked, no added fat',
    'Turkey, breast, lean flesh, skin & fat, raw',
    'Turkey, hindquarter, lean flesh, skin & fat, baked, no added fat',
    'Turkey, hindquarter, lean flesh, skin & fat, raw',
    'Turkey, hindquarter, lean flesh, baked, no added fat',
    'Turkey, hindquarter, lean flesh, raw',
    'Kangaroo, rump, baked, no added fat',
    'Kangaroo, steak, as purchased, fried, no added fat',
    'Venison, leg medallion, lean, baked, roasted, fried, stir-fried, grilled or BBQ\'d, no added fat',
    'Venison, mince, premium, baked, roasted, fried, stir-fried, grilled or BBQ\'d, no added fat',
    'Chicken, processed luncheon meat, low or reduced fat',
    'Chicken, schnitzel, baked without fat',
    'Chicken, nugget, purchased frozen, baked, no added fat',
    'Ham, leg, sliced, reduced fat',
    'Egg, chicken, whole, omega-3 polyunsaturate enriched, boiled',
    'Egg, chicken, whole, omega-3 polyunsaturate enriched, raw',
    'Egg, chicken, whole,fried, no fat added',
    'Egg, chicken, whole, hard-boiled',
    'Egg, chicken, whole, poached',
    'Egg, chicken, whole, scrambled, with regular fat cow\'s milk, no fat added',
    'Egg, chicken, white (albumen), hard-boiled',
    'Egg, chicken, yolk, hard-boiled',
    'Eggplant (aubergine), fresh, stir-fried, no added fat',
    'Capsicum, green, fresh, fried, no added fat',
    'Capsicum, red, fresh, fried, no added fat',
    'Kale, fried, no added fat',
    'Garlic, peeled, fresh, fried, no added fat',
    'Broccoli, fresh, baked, no added fat',
    'Broccoli, fresh, boiled, drained',
    'Broccoli, fresh, microwaved',
    'Broccolini, fresh, boiled, drained',
    'Brussels sprout, fresh, boiled, drained',
    'Bok choy, fresh, boiled, drained',
    'Silverbeet, fresh, boiled, drained',
    'Spinach, Mature English, fresh, boiled, drained',
    'Cauliflower, fresh, boiled, drained',
    'Cabbage, Chinese (wombok), raw',
    'Cabbage, red, raw',
    'Cabbage, savoy, raw',
    'Asparagus, green, boiled, drained',
    'Asparagus, green, fresh or frozen, baked, roasted, stir-fried or fried, grilled or BBQ\'d, no added fat',
    'Leek, fresh, raw',
    'Celery, fresh, raw',
    'Cucumber, common, peeled, raw',
    'Cucumber, Lebanese, peeled, raw',
    'Cucumber, Lebanese, unpeeled, raw',
    'Cucumber, telegraph, unpeeled, raw',
    'Lettuce, mignonette, raw',
    'Pea, green, fresh or frozen, boiled, drained',
    'Green bean, fresh, boiled, drained',
    'Zucchini, golden, fresh, unpeeled, boiled, drained',
    'Zucchini, golden, fresh, unpeeled, raw',
    'Zucchini, green skin, fresh, unpeeled, boiled, drained',
    'Zucchini, green skin, fresh, unpeeled, fried, no added fat',
    'Sweet potato, orange flesh, peeled, fresh, baked, no added fat',
    'Sweet potato, orange flesh, peeled, fresh, boiled, drained',
    'Sweet potato, orange flesh, unpeeled, raw',
    'Sweet potato, purple flesh, peeled, baked, no added fat',
    'Sweet potato, purple flesh, peeled, raw',
    'Sweet potato, white flesh, peeled or unpeeled, fresh or frozen, baked, roasted, fried, stir-fried, grilled or BBQ\'d, no added fat',
    'Sweet potato, white flesh, peeled, raw',
    'Sweetcorn, fresh, boiled, drained',
    'Pumpkin, butternut, peeled, baked, no added fat',
    'Pumpkin, Queensland blue, peeled, baked, no added fat',
    'Pumpkin, Queensland blue, peeled, raw',
    'Carrot, baby, peeled, fresh, boiled, drained',
    'Carrot, mature, peeled, fresh, boiled, drained',
    'Tomato, whole, canned in tomato juice, drained',
    'Tomato, paste, with added salt',
    'Beetroot, canned, drained',
    'Potato, chips, regular, fast food outlet, deep fried, blended oil, salted',
    'Potato, chips, regular, fast food outlet, deep fried, monounsaturated oil, salted',
    'Potato, chips, regular, independent takeaway outlet, deep fried, blended oil, salted',
    'Potato, chips, regular, purchased frozen, baked, no added fat',
    'Potato, coliban, peeled, baked, no added fat',
    'Potato, coliban, peeled, boiled, drained',
    'Potato, desiree, peeled, baked, no added fat',
    'Potato, desiree, peeled, boiled, drained',
    'Potato, new, peeled, baked, no added fat',
    'Potato, new, peeled, boiled, drained',
    'Potato, pale skin, peeled, baked, no added fat',
    'Potato, pale skin, peeled, boiled, drained',
    'Potato, pontiac, peeled, baked, no added fat',
    'Potato, pontiac, peeled, boiled, drained',
    'Potato, red skin, peeled, baked, no added fat',
    'Potato, red skin, peeled, boiled, drained',
    'Potato, sebago, peeled, baked, no added fat',
    'Potato, sebago, peeled, boiled, drained',
    'Avocado, shepard, raw',
    'Apple, bonza, unpeeled, raw',
    'Apple, golden delicious, unpeeled, raw',
    'Apple, green skin, unpeeled, raw',
    'Apple, jonathan, unpeeled, raw',
    'Apple, red delicious, unpeeled, raw',
    'Apple, red skin, peeled, raw',
    'Apple, red skin, unpeeled, raw',
    'Apple, royal gala, unpeeled, raw',
    'Banana, frozen',
    'Banana, lady finger or sugar, peeled, raw',
    'Grape, red globe, raw',
    'Mandarin, imperial, peeled, raw',
    'Orange, navel, peeled, raw',
    'Orange, valencia, peeled, raw',
    'Pear, brown skin, unpeeled, raw',
    'Pear, nashi, unpeeled, raw',
    'Pear, Packham\'s triumph, unpeeled, raw',
    'Pear, William Bartlett, unpeeled, raw',
    'Peach, white, unpeeled, raw',
    'Kiwifruit, gold, peeled, raw',
    'Passionfruit, raw',
    'Mango, peeled, frozen',
    'Strawberry, purchased frozen',
    'Blueberry, purchased frozen',
    'Raspberry, raw',
    'Cherry, dark, raw',
    'Blackberry, raw',
    'Almond beverage, added sugar & Ca',
    'Almond beverage, added sugar & vitamins B1, B2, B12, C & Ca',
    'Almond beverage, added sugar, unfortified',
    'Almond beverage, no added sugar, added Ca',
    'Soy beverage, added sugar, unfortified',
    'Rice beverage, no added sugar',
    'Coconut beverage, no added sugar',
    'Milk, cow, fluid, lactose free, reduced fat (~1%)',
    'Milk, cow, fluid, lactose free, regular fat (~3.5%)',
    'Milk, cow, fluid, reduced fat (~1.5%), added omega 3 polyunsaturates',
    'Milk, cow, fluid, regular fat (~3.5%), added omega 3 polyunsaturates',
    'Milk, cow, canned, evaporated, reduced fat (~2%)',
    'Milk, cow, canned, evaporated, regular',
    'Protein powder, hemp seed based',
    'Protein powder, whey based, protein >70%, unfortified, prepared with water',
    'Nut, almond, with skin, roasted, unsalted',
    'Nut, cashew, roasted, salted',
    'Nut, cashew, roasted, unsalted',
    'Seed, linseed or flaxseed',
    'Seed, sesame, unsalted',
    'Peanut butter, smooth & crunchy, added sugar & salt',
    'Bread roll, topped with cheese',
    'Bread roll, topped with cheese & bacon',
    'Bun, hamburger or hot dog, from white flour, commercial',
    'Bread, from white flour, added fibre',
    'Bread, from white flour, added omega-3 polyunsaturates',
    'Bread, from white flour, Italian-style, commercial',
    'Bread, from white flour, sour dough, commercial',
    'Bread, from white flour, Turkish',
    'Bread, from rye flour, sour dough',
    'Bread, flat wrap or tortilla, corn, commercial',
    'Bread, tortilla, white, commercial',
    'Bread, wrap, white, commercial',
    'Bread, Naan, commercial',
    'Breakfast cereal, bran flakes',
    'Breakfast cereal, corn flakes',
    'Breakfast cereal, high fibre bran',
    'Breakfast cereal, mixed grain flakes',
    'Breakfast cereal, muesli, untoasted',
    'Breakfast cereal, puffed rice',
    'Breakfast cereal, puffed wheat',
    'Breakfast cereal, rice flakes',
    'Oats, hulled, uncooked',
    'Barley, pearl, boiled, no added fat or salt',
    'Quinoa, boiled, no added fat or salt',
    'Rice, brown, boiled, no added salt',
    'Rice, white, boiled or rice cooker, no added salt',
    'Pasta, white wheat flour & egg, boiled from dry, no added salt',
    'Pasta, white wheat flour, boiled from dry, no added salt',
    'Pasta, wholemeal wheat flour, boiled from dry, no added salt',
    'Couscous, boiled, no added fat or salt',
    'Beef, diced, lean, casseroled, no added fat',
    'Beef, diced, lean, dry-fried, no added fat',
    'Beef, mince, lower fat, stir-fried, no added fat',
    'Beef, rump steak, lean, BBQ\'d, no added fat',
    'Beef, scotch fillet (rib eye), lean, BBQ\'d, no added fat',
    'Beef, sirloin (porterhouse), lean, BBQ\'d, no added fat',
    'Beef, stir-fry strips, lean, dry-fried, no added fat',
    'Beef, T-bone steak, lean, BBQ\'d, no added fat',
    'Beef, tenderloin (eye fillet), lean, BBQ\'d, no added fat',
    'Beef, topside steak, lean, BBQ\'d, no added fat',
    'Lamb, diced, lean, casseroled, no added fat',
    'Lamb, diced, lean, stir-fried, no added fat',
    'Lamb, leg, lean, baked, no added fat',
    'Lamb, loin chop, lean, grilled, no added fat',
    'Lamb, rack, lean, baked, no added fat',
    'Lamb, shoulder, lean, baked, no added fat',
    'Lamb, strips, lean, stir-fried, no added fat',
    'Lamb, mince, lean, stir-fried, no added fat',
    'Lamb, cutlet or frenched cutlet, with bone, lean, grilled, no added fat',
    'Pork, belly, rind removed, raw',
    'Pork, fillet, lean, baked, no added fat',
    'Pork, forequarter chop, lean, BBQ\'d, no added fat',
    'Pork, loin chop, lean, BBQ\'d, no added fat',
    'Pork, medallion or loin steak, lean, fried, no added fat',
    'Pork, rump steak, lean, fried, no added fat',
    'Pork, butterfly steak, lean, grilled, no added fat',
    'Pork, mince, as purchased, fried, no added fat',
    'Veal, cutlet, with bone, lean, grilled, no added fat',
    'Veal, diced, lean, stir-fried, no added fat',
    'Veal, steak, boneless, leg, lean, grilled, no added fat',
    'Veal, stir-fry strips, lean, stir-fried, no added fat',
    'Chicken, breast, lean flesh, casseroled, no added fat',
    'Chicken, breast, lean flesh, fried, no added fat',
    'Chicken, breast, lean flesh, grilled, no added fat',
    'Chicken, drumstick, lean flesh, casseroled, no added fat',
    'Chicken, drumstick, lean flesh, baked, no added fat',
    'Chicken, thigh, lean flesh, casseroled, no added fat',
    'Chicken, thigh, lean flesh, fried, no added fat',
    'Chicken, thigh, lean flesh, baked, no added fat',
    'Chicken, wing, lean flesh, casseroled, no added fat',
    'Chicken, wing, lean flesh, baked, no added fat',
    'Chicken, mince, fried, no added fat',
    'Chicken, liver, fried, added butter',
    'Turkey, breast, lean flesh, baked, no added fat',
    'Kangaroo, loin fillet, grilled, no added fat',
    'Kangaroo, rump, raw',
    'Kangaroo, steak, as purchased, raw',
    'Venison, leg medallion, lean, raw',
    'Venison, mince, premium, raw',
    'Barramundi, aquacultured, fillet, grilled, no added fat',
    'Salmon, Atlantic, fillet, grilled, no added fat',
    'Salmon, Pacific King, fillet, skinless, grilled, no added fat',
    'Tuna, yellowfin, fillet, baked, no added fat',
    'Tuna, yellowfin, fillet, steamed, no added fat',
    'Trout, ocean, aquacultured, fillet, without skin, baked, no added fat',
    'Trout, rainbow, aquacultured, baked, no added fat',
    'Tilapia, fillet, baked, no added fat',
    'Bream, fillet, baked, no added fat',
    'Flathead, fillet, baked, no added fat',
    'Snapper, fillet, baked, no added fat',
    'Whiting, King George, fillet, baked, no added fat',
    'Blue grenadier (hoki), fillet, baked, no added fat',
    'Bassa (basa), fillet, baked, no added fat',
    'Silver perch, fillet, baked, no added fat',
    'Shark, gummy, fillet, baked, no added fat',
}

# ─────────────────────────────────────────────────────────────────────────────
# STEP 2: Name simplification mapping
# Maps original AFCD name → simplified display name
# ─────────────────────────────────────────────────────────────────────────────

NAME_MAP = {
    # ── FRUITS ────────────────────────────────────────────────────────────────
    'Apple, fuji, unpeeled, raw': 'Apple, raw',
    'Apple, pink lady, unpeeled, raw': 'Apple, pink lady, raw',
    'Apple, granny-smith, unpeeled, raw': 'Apple, granny smith, raw',
    'Avocado, hass, raw': 'Avocado, raw',
    'Banana, cavendish, peeled, raw': 'Banana, raw',
    'Blueberry, raw': 'Blueberry, raw',
    'Cherry, dark, raw': 'Cherry, raw',
    'Grape, green, raw': 'Grape, green, raw',
    'Kiwifruit, green (hayward), peeled, raw': 'Kiwifruit, raw',
    'Mandarin, peeled, raw': 'Mandarin, raw',
    'Mango, peeled, raw': 'Mango, raw',
    'Orange, peeled, raw': 'Orange, raw',
    'Peach, yellow, unpeeled, raw': 'Peach, raw',
    'Pear, green skin, unpeeled, raw': 'Pear, raw',
    'Pineapple, peeled, raw': 'Pineapple, raw',
    'Plum, raw': 'Plum, raw',
    'Raspberry, raw': 'Raspberry, raw',
    'Strawberry, raw': 'Strawberry, raw',
    'Blackberry, raw': 'Blackberry, raw',
    'Grapefruit, pink flesh, peeled, raw': 'Grapefruit, raw',
    'Lychee, raw': 'Lychee, raw',
    'Pomegranate, raw': 'Pomegranate, raw',
    'Papaya (pawpaw), raw': 'Papaya, raw',
    'Rockmelon (cantaloupe), peeled, raw': 'Rockmelon, raw',
    'Honeydew melon, peeled, raw': 'Honeydew melon, raw',
    'Tangelo, peeled, raw': 'Tangelo, raw',
    'Tangerine or tangor, peeled, raw': 'Mandarin, raw',  # consolidate
    'Nectarine, raw': 'Nectarine, raw',
    'Fig, raw': 'Fig, raw',
    'Date, medjool, raw': 'Date, medjool, raw',
    'Passionfruit, raw': 'Passionfruit, raw',
    'Lemon, peeled, raw': 'Lemon, raw',
    'Lime, peeled, raw': 'Lime, raw',
    'Apricot, raw': 'Apricot, raw',
    'Apricot, dried': 'Apricot, dried',
    'Date, raw': 'Date, raw',
    'Fig, dried': 'Fig, dried',
    'Prune (dried plum)': 'Prune, dried',
    'Raisin': 'Raisin',
    'Sultana': 'Sultana',
    'Apple, dried': 'Apple, dried',
    'Coconut, flesh, fresh, raw': 'Coconut flesh, raw',
    'Coconut, desiccated, unsweetened': 'Coconut, desiccated',
    'Coconut, shredded, sweetened': 'Coconut, shredded (sweetened)',
    'Mango, peeled, frozen': 'Mango, frozen',
    'Strawberry, purchased frozen': 'Strawberry, frozen',
    'Blueberry, purchased frozen': 'Blueberry, frozen',
    'Pineapple, peeled, frozen': 'Pineapple, frozen',
    'Banana, frozen': 'Banana, frozen',
    'Pineapple, canned in juice, drained': 'Pineapple, canned in juice',
    # ── VEGETABLES ────────────────────────────────────────────────────────────
    'Asparagus, green, raw': 'Asparagus, raw',
    'Beetroot, raw': 'Beetroot, raw',
    'Beetroot, canned, drained': 'Beetroot, canned',
    'Bok choy, fresh, raw': 'Bok choy, raw',
    'Broccoli, fresh, raw': 'Broccoli, raw',
    'Broccolini, fresh, raw': 'Broccolini, raw',
    'Brussels sprout, fresh, raw': 'Brussels sprouts, raw',
    'Cabbage, white, raw': 'Cabbage, raw',
    'Capsicum, green, fresh, raw': 'Capsicum, green, raw',
    'Capsicum, red, fresh, raw': 'Capsicum, red, raw',
    'Capsicum, yellow, fresh, raw': 'Capsicum, yellow, raw',
    'Carrot, mature, peeled, fresh, raw': 'Carrot, raw',
    'Carrot, baby, peeled, fresh, raw': 'Carrot, baby, raw',
    'Cauliflower, fresh, raw': 'Cauliflower, raw',
    'Celery, fresh, raw': 'Celery, raw',
    'Cucumber, common, unpeeled, raw': 'Cucumber, raw',
    'Eggplant (aubergine), fresh, raw': 'Eggplant, raw',
    'Fennel bulb, raw': 'Fennel, raw',
    'Garlic, peeled, fresh, raw': 'Garlic, raw',
    'Ginger, fresh, raw': 'Ginger, fresh',
    'Green bean, fresh, raw': 'Green beans, raw',
    'Kale, raw': 'Kale, raw',
    'Leek, fresh, raw': 'Leek, raw',
    'Lettuce, cos, raw': 'Lettuce, cos, raw',
    'Lettuce, iceberg, raw': 'Lettuce, iceberg, raw',
    'Mushroom, common, raw': 'Mushroom, raw',
    'Onion, mature, peeled, fresh, raw': 'Onion, raw',
    'Onion, spring (shallot), raw': 'Spring onion, raw',
    'Pea, green, fresh or frozen, raw': 'Peas, raw',
    'Pumpkin, butternut, peeled, raw': 'Pumpkin, butternut, raw',
    'Rocket, raw': 'Rocket, raw',
    'Shallot, raw': 'Shallot, raw',
    'Silverbeet, fresh, raw': 'Silverbeet, raw',
    'Snow pea, fresh, raw': 'Snow peas, raw',
    'Spinach, baby, fresh, raw': 'Spinach, baby, raw',
    'Spinach, Mature English, fresh, raw': 'Spinach, raw',
    'Spinach, water, fresh, raw': 'Water spinach, raw',
    'Sweet potato, orange flesh, peeled, fresh, raw': 'Sweet potato, raw',
    'Sweetcorn, fresh, raw': 'Sweetcorn, raw',
    'Tomato, cherry, raw': 'Tomato, cherry, raw',
    'Tomato, common, raw': 'Tomato, raw',
    'Tomato, paste, with added salt': 'Tomato paste',
    'Tomato, paste, no added salt': 'Tomato paste, no added salt',
    'Tomato, whole, canned in tomato juice, drained': 'Tomato, canned (drained)',
    'Tomato, whole, canned in tomato juice, undrained': 'Tomato, canned',
    'Tomato, puree, commercial': 'Tomato puree',
    'Tomato, sundried': 'Tomato, sundried',
    'Zucchini, green skin, fresh, unpeeled, raw': 'Zucchini, raw',
    'Potato, coliban, peeled, raw': 'Potato, raw',
    'Potato, desiree, peeled, raw': 'Potato, desiree, raw',
    'Potato, new, peeled, raw': 'Potato, new, raw',
    'Potato, pale skin, peeled, raw': 'Potato, raw',
    'Potato, pontiac, peeled, raw': 'Potato, pontiac, raw',
    'Potato, red skin, peeled, raw': 'Potato, red skin, raw',
    'Potato, sebago, peeled, raw': 'Potato, sebago, raw',
    'Bean sprout, mung, raw': 'Bean sprouts, raw',
    'Chilli (chili), fresh, red, raw': 'Chilli, fresh, raw',
    'Basil, green, fresh, raw': 'Basil, fresh',
    'Coriander (cilantro), fresh, raw': 'Coriander, fresh',
    'Parsley, fresh, raw': 'Parsley, fresh',
    'Chives, fresh, raw': 'Chives, fresh',
    'Rosemary, fresh, raw': 'Rosemary, fresh',
    'Thyme, fresh, raw': 'Thyme, fresh',
    'Watercress, raw': 'Watercress, raw',
    'Sprout, alfalfa, raw': 'Alfalfa sprouts, raw',
    'Sprout, broccoli, raw': 'Broccoli sprouts, raw',
    'Squash, button, raw': 'Button squash, raw',
    'Celeriac, peeled, fresh, raw': 'Celeriac, raw',
    'Artichoke, globe, raw': 'Artichoke, raw',
    'Artichoke, globe, boiled, drained': 'Artichoke, cooked',
    'Artichoke heart, canned in brine, drained': 'Artichoke hearts, canned',
    'Artichoke, jerusalem, peeled, raw': 'Jerusalem artichoke, raw',
    'Bamboo shoot, canned in water, heated, drained': 'Bamboo shoots, canned',
    'Water chestnut, peeled, canned, drained': 'Water chestnuts, canned',
    'Leek, fresh, boiled, drained': 'Leek, cooked',
    'Fennel bulb, raw': 'Fennel, raw',
    'Radish, red, raw': 'Radish, raw',
    'Swede, peeled, fresh, raw': 'Swede, raw',
    'Turnip, white, peeled, fresh, raw': 'Turnip, raw',
    'Chicory or endive, raw': 'Chicory, raw',
    'Rhubarb, raw': 'Rhubarb, raw',
    'Choko, peeled, raw': 'Choko, raw',
    # ── MEATS ─────────────────────────────────────────────────────────────────
    'Beef, diced, lean, raw': 'Beef, diced, lean, raw',
    'Beef, mince, lower fat, raw': 'Beef mince, lean, raw',
    'Beef, rump steak, lean, raw': 'Beef rump steak, lean, raw',
    'Beef, scotch fillet (rib eye), lean, raw': 'Beef scotch fillet, lean, raw',
    'Beef, sirloin (porterhouse), lean, raw': 'Beef sirloin, lean, raw',
    'Beef, stir-fry strips, lean, raw': 'Beef stir-fry strips, lean, raw',
    'Beef, T-bone steak, lean, raw': 'Beef T-bone steak, lean, raw',
    'Beef, tenderloin (eye fillet), lean, raw': 'Beef eye fillet, lean, raw',
    'Beef, topside steak, lean, raw': 'Beef topside steak, lean, raw',
    'Lamb, cutlet or frenched cutlet, with bone, lean, raw': 'Lamb cutlet, lean, raw',
    'Lamb, diced, lean, raw': 'Lamb, diced, lean, raw',
    'Lamb, leg, lean, raw': 'Lamb leg, lean, raw',
    'Lamb, loin chop, lean, raw': 'Lamb loin chop, lean, raw',
    'Lamb, mince, lean, raw': 'Lamb mince, lean, raw',
    'Lamb, rack, lean, raw': 'Lamb rack, lean, raw',
    'Lamb, shoulder, lean, raw': 'Lamb shoulder, lean, raw',
    'Lamb, strips, lean, raw': 'Lamb stir-fry strips, lean, raw',
    'Pork, belly, rind removed, raw': 'Pork belly, raw',
    'Pork, butterfly steak, lean, raw': 'Pork butterfly steak, lean, raw',
    'Pork, fillet, lean, raw': 'Pork fillet, lean, raw',
    'Pork, forequarter chop, lean, raw': 'Pork forequarter chop, lean, raw',
    'Pork, loin chop, lean, raw': 'Pork loin chop, lean, raw',
    'Pork, medallion or loin steak, lean, raw': 'Pork loin steak, lean, raw',
    'Pork, mince, untrimmed, raw': 'Pork mince, raw',
    'Pork, rump steak, lean, raw': 'Pork rump steak, lean, raw',
    'Pork, strips, untrimmed, raw': 'Pork stir-fry strips, raw',
    'Veal, cutlet, with bone, lean, raw': 'Veal cutlet, lean, raw',
    'Veal, diced, lean, raw': 'Veal, diced, lean, raw',
    'Veal, steak, boneless, leg, lean, raw': 'Veal steak, lean, raw',
    'Veal, stir-fry strips, lean, raw': 'Veal stir-fry strips, lean, raw',
    'Chicken, breast, lean flesh, raw': 'Chicken breast, lean, raw',
    'Chicken, drumstick, lean flesh, raw': 'Chicken drumstick, lean, raw',
    'Chicken, liver, raw': 'Chicken liver, raw',
    'Chicken, mince, raw': 'Chicken mince, raw',
    'Chicken, thigh, lean flesh, raw': 'Chicken thigh, lean, raw',
    'Chicken, wing, lean flesh, raw': 'Chicken wing, lean, raw',
    'Turkey, breast, lean flesh, raw': 'Turkey breast, lean, raw',
    'Kangaroo, loin fillet, raw': 'Kangaroo loin fillet, raw',
    'Kangaroo, steak, as purchased, raw': 'Kangaroo steak, raw',
    'Venison, leg medallion, lean, raw': 'Venison leg, lean, raw',
    'Venison, mince, premium, raw': 'Venison mince, raw',
    'Bacon, middle rasher, untrimmed, raw': 'Bacon, raw',
    'Bacon, middle rasher, untrimmed, baked, roasted, fried, grilled or BBQ\'d, no added fat': 'Bacon, cooked',
    'Bacon, middle rasher, separable lean, fried, no added fat': 'Bacon, lean, cooked',
    'Bacon, middle rasher, separable fat, fried, no added fat': 'Bacon fat, cooked',
    'Bacon, shortcut, as purchased without rind, fried, no added fat': 'Bacon, shortcut, cooked',
    'Ham, leg, sliced, regular fat': 'Ham, sliced',
    'Salami, regular fat': 'Salami',
    'Prosciutto, dry cured': 'Prosciutto',
    'Chicken, processed luncheon meat, low or reduced fat': 'Chicken deli meat',
    'Sausage, beef, thick, grilled or BBQ\'d, no added fat': 'Beef sausage, thick, cooked',
    'Sausage, beef, thin, grilled or BBQ\'d, no added fat': 'Beef sausage, thin, cooked',
    'Sausage, chicken, thick, grilled or BBQ\'d, no added fat': 'Chicken sausage, cooked',
    'Sausage, pork, thick, grilled or BBQ\'d, no added fat': 'Pork sausage, cooked',
    # ── FISH & SEAFOOD ────────────────────────────────────────────────────────
    'Barramundi, aquacultured, fillet, raw': 'Barramundi fillet, raw',
    'Bassa (basa), fillet, raw': 'Basa fillet, raw',
    'Blue grenadier (hoki), fillet, raw': 'Hoki fillet, raw',
    'Bream, fillet, raw': 'Bream fillet, raw',
    'Flathead, fillet, raw': 'Flathead fillet, raw',
    'Salmon, Atlantic, fillet, raw': 'Salmon (Atlantic) fillet, raw',
    'Salmon, Pacific King, fillet, skinless, raw': 'Salmon (King) fillet, raw',
    'Salmon, pink, canned in brine, drained': 'Salmon, pink, canned',
    'Salmon, red, canned in brine, drained': 'Salmon, red, canned',
    'Salmon, smoked, sliced': 'Salmon, smoked',
    'Sardine, Australian, whole, raw': 'Sardine, raw',
    'Shark, gummy, fillet, raw': 'Shark (gummy) fillet, raw',
    'Silver perch, fillet, raw': 'Silver perch fillet, raw',
    'Snapper, fillet, raw': 'Snapper fillet, raw',
    'Tilapia, fillet, raw': 'Tilapia fillet, raw',
    'Trout, ocean, aquacultured, fillet, without skin, raw': 'Ocean trout fillet, raw',
    'Trout, rainbow, aquacultured, raw': 'Rainbow trout, raw',
    'Tuna, canned in brine, drained': 'Tuna, canned in brine',
    'Tuna, unflavoured, canned in water, drained': 'Tuna, canned in water',
    'Tuna, yellowfin, fillet, raw': 'Tuna (yellowfin) fillet, raw',
    'Whiting, King George, fillet, raw': 'Whiting fillet, raw',
    'Anchovy, canned in oil, drained': 'Anchovy, canned',
    'Crab, flesh, purchased steamed or boiled': 'Crab, cooked',
    'Lobster or crayfish, flesh, purchased steamed, poached or boiled, no added fat': 'Lobster, cooked',
    'Lobster, southern rock, wild, flesh, raw': 'Lobster, raw',
    'Mussel, blue, steamed': 'Mussels, cooked',
    'Octopus, raw': 'Octopus, raw',
    'Oyster, aquacultured, raw': 'Oyster, raw',
    'Prawn, flesh, raw (green)': 'Prawn, raw',
    'Prawn, flesh, purchased cooked': 'Prawn, cooked',
    'Scallop, commercial, steamed': 'Scallop, cooked',
    'Squid or calamari, raw': 'Calamari, raw',
    # ── DAIRY & EGGS ──────────────────────────────────────────────────────────
    'Butter, plain, no added salt': 'Butter, unsalted',
    'Butter, plain, reduced salt': 'Butter, reduced salt',
    'Butter, plain, salted': 'Butter, salted',
    'Cheese, blue vein': 'Cheese, blue vein',
    'Cheese, bocconcini': 'Cheese, bocconcini',
    'Cheese, brie': 'Cheese, brie',
    'Cheese, camembert': 'Cheese, camembert',
    'Cheese, cheddar, natural, reduced fat (~25%)': 'Cheese, cheddar, reduced fat',
    'Cheese, cheddar, natural, regular fat': 'Cheese, cheddar',
    'Cheese, cottage': 'Cheese, cottage',
    'Cheese, cream, plain': 'Cream cheese',
    'Cheese, edam': 'Cheese, edam',
    'Cheese, fetta (feta)': 'Cheese, feta',
    'Cheese, goat, firm': 'Cheese, goat',
    'Cheese, haloumi (halloumi)': 'Cheese, haloumi',
    'Cheese, haloumi (halloumi), reduced salt': 'Cheese, haloumi, reduced salt',
    'Cheese, mozzarella': 'Cheese, mozzarella',
    'Cheese, parmesan, dried, finely grated': 'Cheese, parmesan, grated',
    'Cheese, parmesan, fresh, regular fat': 'Cheese, parmesan, fresh',
    'Cheese, ricotta': 'Cheese, ricotta',
    'Cream, sour, light (~18% fat)': 'Sour cream, light',
    'Cream, sour, regular fat': 'Sour cream',
    'Cream, thickened, regular fat (~35%)': 'Cream, thickened',
    'Egg, chicken, white (albumen), raw': 'Egg white, raw',
    'Egg, chicken, whole, raw': 'Egg, whole, raw',
    'Egg, chicken, yolk, raw': 'Egg yolk, raw',
    'Milk, cow, fluid, reduced fat (~1%)': 'Milk, reduced fat',
    'Milk, cow, fluid, regular fat (~3.5%)': 'Milk, full fat',
    'Milk, cow, fluid, skim (~0.15% fat)': 'Milk, skim',
    'Milk, cow, canned, evaporated, regular': 'Milk, evaporated',
    'Yoghurt, apricot pieces or flavoured, regular fat (~3%)': 'Yoghurt, fruit flavoured',
    'Yoghurt, flavoured, high fat (~5%)': 'Yoghurt, flavoured, high fat',
    'Yoghurt, flavoured, low fat (0.2%), intense sweetened, increased protein': 'Yoghurt, high protein, low fat',
    'Yoghurt, flavoured, low fat (~2%)': 'Yoghurt, flavoured, low fat',
    'Yoghurt, natural, regular fat (~3%)': 'Yoghurt, natural',
    'Yoghurt, strawberry pieces or flavoured, regular fat (~3%)': 'Yoghurt, strawberry flavoured',
    'Yoghurt, vanilla flavoured (~2%)': 'Yoghurt, vanilla flavoured',
    'Yoghurt, vanilla flavoured, low fat (<0.5%)': 'Yoghurt, vanilla, low fat',
    'Protein powder, whey based, protein >70%, unfortified': 'Protein powder, whey',
    # ── GRAINS & BREAD ────────────────────────────────────────────────────────
    'Bagel, from white flour, commercial': 'Bagel, white',
    'Barley, pearl, uncooked': 'Barley, pearl, dry',
    'Bread roll, from white flour': 'Bread roll, white',
    'Bread roll, from wholemeal flour': 'Bread roll, wholemeal',
    'Bread roll, mixed grain': 'Bread roll, mixed grain',
    'Bread, flat (pita or Lebanese), white, commercial': 'Pita bread, white',
    'Bread, flat (pita or Lebanese), wholemeal, commercial': 'Pita bread, wholemeal',
    'Bread, from rye flour, sour dough': 'Bread, rye sourdough',
    'Bread, from white flour': 'Bread, white',
    'Bread, from white flour, Italian-style, commercial': 'Bread, Italian white',
    'Bread, from white flour, sour dough, commercial': 'Bread, white sourdough',
    'Bread, from white flour, Turkish': 'Bread, Turkish',
    'Bread, from wholemeal flour': 'Bread, wholemeal',
    'Bread, gluten free': 'Bread, gluten free',
    'Bread, mixed grain': 'Bread, mixed grain',
    'Bread, Naan, commercial': 'Naan bread',
    'Bread, tortilla, white, commercial': 'Tortilla wrap, white',
    'Bread, wrap, white, commercial': 'Wrap, white',
    'Breadcrumbs, white': 'Breadcrumbs',
    'Breakfast cereal, wheat biscuit': 'Weet-Bix style cereal',
    'Buckwheat groats, uncooked': 'Buckwheat, dry',
    'Bulgur (burghul), uncooked': 'Bulgur wheat, dry',
    'Bun, hamburger or hot dog, from white flour, commercial': 'Burger bun, white',
    'Couscous, boiled, no added fat or salt': 'Couscous, cooked',
    'Couscous, uncooked': 'Couscous, dry',
    'Crumpet, commercial': 'Crumpet',
    'Flour, plain, white wheat': 'Flour, plain white',
    'Flour, self-raising, white wheat': 'Flour, self-raising',
    'Flour, wholemeal wheat': 'Flour, wholemeal',
    'Oat bran, unprocessed, uncooked': 'Oat bran',
    'Oats, rolled, uncooked': 'Oats, rolled, dry',
    'Pasta, white wheat flour, dry': 'Pasta, white, dry',
    'Pasta, white wheat flour & egg, boiled from dry, no added salt': 'Pasta, egg, cooked',
    'Pasta, white wheat flour, boiled from dry, no added salt': 'Pasta, white, cooked',
    'Pasta, wholemeal wheat flour, boiled from dry, no added salt': 'Pasta, wholemeal, cooked',
    'Pasta, wholemeal wheat flour, dry': 'Pasta, wholemeal, dry',
    'Quinoa, uncooked': 'Quinoa, dry',
    'Rice, brown, uncooked': 'Rice, brown, dry',
    'Rice, white, uncooked': 'Rice, white, dry',
    'Semolina, uncooked': 'Semolina, dry',
    'Taco shell, corn, commercial': 'Taco shell',
    'Wheat bran, unprocessed, uncooked': 'Wheat bran',
    'Wheat germ': 'Wheat germ',
    'Rice cake, plain': 'Rice cake',
    'Corn thins': 'Corn thins',
    'Barley, pearl, boiled, no added fat or salt': 'Barley, pearl, cooked',
    'Quinoa, boiled, no added fat or salt': 'Quinoa, cooked',
    'Rice, brown, boiled, no added salt': 'Rice, brown, cooked',
    'Rice, white, boiled or rice cooker, no added salt': 'Rice, white, cooked',
    'Bulgur (burghul), uncooked': 'Bulgur wheat, dry',
    'Amaranth, grain, whole, uncooked': 'Amaranth, dry',
    'Teff, uncooked': 'Teff, dry',
    'Spelt, grain, uncooked': 'Spelt grain, dry',
    'Sorghum, grain, uncooked': 'Sorghum, dry',
    'Rye, grain, uncooked': 'Rye grain, dry',
    'Triticale, grain, uncooked': 'Triticale, dry',
    'Buckwheat groats, uncooked': 'Buckwheat, dry',
    'Wheat, whole, uncooked': 'Wheat grain, dry',
    'Semolina, uncooked': 'Semolina, dry',
    'Noodle, buckwheat (soba), boiled, no added fat': 'Soba noodles, cooked',
    'Noodle, rice, dry': 'Rice noodles, dry',
    'Noodle, wheat, plain, dry': 'Wheat noodles, dry',
    'Breakfast cereal, muesli, untoasted': 'Muesli, untoasted',
    'Breakfast cereal, muesli, toasted': 'Muesli, toasted',
    'Oats, hulled, uncooked': 'Oats, hulled, dry',
    # ── LEGUMES ───────────────────────────────────────────────────────────────
    'Bean, adzuki, dried, boiled, drained': 'Adzuki beans, cooked',
    'Bean, black, dried, boiled, drained': 'Black beans, cooked',
    'Bean, borlotti, canned, drained': 'Borlotti beans, canned',
    'Bean, borlotti, dried, boiled, drained': 'Borlotti beans, cooked',
    'Bean, butter, canned, drained': 'Butter beans, canned',
    'Bean, cannellini, canned, drained': 'Cannellini beans, canned',
    'Bean, cannellini, dried, boiled, drained': 'Cannellini beans, cooked',
    'Bean, kidney, canned, drained': 'Kidney beans, canned',
    'Bean, kidney, dried, boiled, drained': 'Kidney beans, cooked',
    'Bean, lima, dried, boiled, drained': 'Lima beans, cooked',
    'Bean, mung, dried, boiled, drained': 'Mung beans, cooked',
    'Bean, navy, dried, boiled, drained': 'Navy beans, cooked',
    'Bean, pinto, dried, boiled, drained': 'Pinto beans, cooked',
    'Bean, soy, dried, boiled, drained': 'Soybeans, cooked',
    'Bean, soy, canned, drained': 'Soybeans, canned',
    'Bean sprout, mung, raw': 'Bean sprouts, raw',
    'Baked beans, canned in tomato sauce': 'Baked beans',
    'Baked beans, canned in tomato sauce, reduced salt': 'Baked beans, reduced salt',
    'Chickpea, canned, drained': 'Chickpeas, canned',
    'Chickpea, dried': 'Chickpeas, dry',
    'Chickpea, dried, boiled, drained': 'Chickpeas, cooked',
    'Edamame, frozen, boiled, drained': 'Edamame, cooked',
    'Lentil, dried, boiled, drained': 'Lentils, cooked',
    'Lentil, French, hulled, dry': 'Lentils, French, dry',
    'Lentil, green, hulled, dry': 'Lentils, green, dry',
    'Lentil, hulled, dry': 'Lentils, dry',
    'Lentil, red, hulled, dry': 'Lentils, red, dry',
    'Pea, green, fresh or frozen, raw': 'Peas, raw',
    'Pea, split, yellow, dried, uncooked': 'Split peas, dry',
    'Tofu (soy bean curd), firm, as purchased': 'Tofu, firm',
    'Textured vegetable protein/soy granules': 'TVP / soy mince, dry',
    # ── NUTS & SEEDS ──────────────────────────────────────────────────────────
    'Nut, almond meal': 'Almond meal',
    'Nut, almond, with skin, raw, unsalted': 'Almonds, raw',
    'Nut, almond, with skin, roasted, unsalted': 'Almonds, roasted',
    'Nut, cashew, raw, unsalted': 'Cashews, raw',
    'Nut, cashew, roasted, salted': 'Cashews, roasted, salted',
    'Nut, cashew, roasted, unsalted': 'Cashews, roasted',
    'Nut, hazelnut, raw, unsalted': 'Hazelnuts, raw',
    'Nut, macadamia, raw, unsalted': 'Macadamia nuts, raw',
    'Nut, pecan, raw, unsalted': 'Pecans, raw',
    'Nut, pistachio, raw, unsalted': 'Pistachios, raw',
    'Nut, walnut, raw, unsalted': 'Walnuts, raw',
    'Peanut butter, smooth & crunchy, no added sugar or salt': 'Peanut butter, natural',
    'Peanut butter, smooth & crunchy, added sugar & salt': 'Peanut butter',
    'Seed, chia, dried': 'Chia seeds',
    'Seed, linseed or flaxseed': 'Flaxseeds / linseeds',
    'Seed, sesame, unsalted': 'Sesame seeds',
    'Seed, sunflower, kernels, raw, unsalted': 'Sunflower seeds, raw',
    'Seed, pumpkin, kernels, raw, unsalted': 'Pumpkin seeds, raw',
    'Tahini, sesame seed pulp': 'Tahini',
    # ── OILS & FATS ───────────────────────────────────────────────────────────
    'Ghee, cow\'s milk': 'Ghee',
    'Margarine, polyunsaturated fat, regular': 'Margarine',
    'Margarine, polyunsaturated fat, reduced fat': 'Margarine, reduced fat',
    'Oil, avocado': 'Avocado oil',
    'Oil, canola': 'Canola oil',
    'Oil, coconut': 'Coconut oil',
    'Oil, olive, extra virgin': 'Olive oil, extra virgin',
    'Oil, olive, refined': 'Olive oil, refined',
    'Oil, sunflower': 'Sunflower oil',
    # ── CONDIMENTS ────────────────────────────────────────────────────────────
    'Dip, avocado (guacamole), commercial': 'Guacamole',
    'Dip, hummus (hommus), commercial': 'Hummus',
    'Dip, tzatziki, commercial': 'Tzatziki',
    'Honey, commercial blend': 'Honey',
    'Maple syrup': 'Maple syrup',
    'Mayonnaise, regular fat': 'Mayonnaise',
    'Mayonnaise, reduced fat': 'Mayonnaise, reduced fat',
    'Mustard powder': 'Mustard powder',
    'Sauce, barbecue, commercial': 'BBQ sauce',
    'Sauce, fish, commercial': 'Fish sauce',
    'Sauce, hot chilli, commercial': 'Hot chilli sauce',
    'Sauce, oyster, commercial': 'Oyster sauce',
    'Sauce, soy, commercial': 'Soy sauce',
    'Sauce, sweet chilli, commercial': 'Sweet chilli sauce',
    'Sauce, tomato (ketchup), commercial': 'Tomato sauce (ketchup)',
    'Sauce, worcestershire, commercial': 'Worcestershire sauce',
    'Vinegar (except balsamic vinegar)': 'Vinegar',
    'Vinegar, balsamic': 'Balsamic vinegar',
    'Sugar, white': 'Sugar, white',
    'Sugar, brown': 'Sugar, brown',
    'Sugar, raw (turbinado)': 'Sugar, raw',
    'Treacle or molasses': 'Molasses',
    'Syrup, golden': 'Golden syrup',
    'Jam or jelly, fruit, commercial': 'Jam, fruit',
    'Chutney or relish, fruit based': 'Chutney',
    'Capers, canned in brine, drained': 'Capers',
    'Stock, beef, liquid, commercial': 'Beef stock',
    'Stock, chicken, liquid, commercial': 'Chicken stock',
    'Stock, vegetable, liquid, commercial': 'Vegetable stock',
    # ── SPICES ────────────────────────────────────────────────────────────────
    'Cardamom seed, dried, ground': 'Cardamom, ground',
    'Chilli (chili), dried, ground': 'Chilli powder',
    'Cinnamon, dried, ground': 'Cinnamon, ground',
    'Cloves, dried, ground': 'Cloves, ground',
    'Coriander seed, dried, ground': 'Coriander, ground',
    'Cumin (cummin) seed, dried, ground': 'Cumin, ground',
    'Fenugreek seed, dried': 'Fenugreek',
    'Ginger, dried, ground': 'Ginger, ground',
    'Mustard powder': 'Mustard powder',
    'Sage, dried, ground': 'Sage, dried',
    'Thyme, dried, ground': 'Thyme, dried',
    'Turmeric, dried, ground': 'Turmeric, ground',
    # ── BEVERAGES ─────────────────────────────────────────────────────────────
    'Almond beverage, no added sugar, unfortified': 'Almond milk, unsweetened',
    'Beer, full strength, ~4.8% v/v': 'Beer, full strength',
    'Beer, low alcohol, ~2.7% v/v': 'Beer, low alcohol',
    'Beer, mid strength, ~3.5% v/v': 'Beer, mid strength',
    'Beer, non-alcoholic, <0.5% v/v': 'Beer, non-alcoholic',
    'Cider, alcoholic, ~4.5% v/v': 'Cider',
    'Coconut beverage, no added sugar': 'Coconut milk (beverage), unsweetened',
    'Coffee, espresso, short black, no milk or sugar': 'Coffee, espresso',
    'Coffee, instant, prepared with water': 'Coffee, instant',
    'Rice beverage, no added sugar': 'Rice milk, unsweetened',
    'Soft drink, cola type, regular': 'Cola, regular',
    'Soft drink, cola type, diet or zero sugar': 'Cola, diet',
    'Soft drink, fruit flavoured, regular': 'Soft drink, fruit flavoured',
    'Soy beverage, added Ca': 'Soy milk, with calcium',
    'Soy beverage, no added sugar, unfortified': 'Soy milk, unsweetened',
    'Tea, green, plain, without milk': 'Green tea',
    'Tea, regular, black, brewed from leaf or teabags, without milk': 'Black tea',
    'Wine, fortified, port': 'Port wine',
    'Wine, fortified, sherry, dry style (~1% sugars)': 'Sherry, dry',
    'Wine, fortified, sherry, sweet style (~11% sugars)': 'Sherry, sweet',
    'Wine, red': 'Red wine',
    'Wine, red, cabernet sauvignon': 'Red wine, cabernet sauvignon',
    'Wine, red, merlot': 'Red wine, merlot',
    'Wine, red, pinot noir': 'Red wine, pinot noir',
    'Wine, red, shiraz': 'Red wine, shiraz',
    'Wine, red, sparkling': 'Red wine, sparkling',
    'Wine, rose': 'Rosé wine',
    'Wine, white': 'White wine',
    'Wine, white, chardonnay': 'White wine, chardonnay',
    'Wine, white, riesling': 'White wine, riesling',
    'Wine, white, sauvignon blanc': 'White wine, sauvignon blanc',
    'Wine, white, semillon': 'White wine, semillon',
    'Wine, white, sparkling': 'White wine, sparkling',
    'Wine, white, sweet dessert style': 'Dessert wine',
    'Alcoholic beverage, spirit, ~40% v/v, all (Brandy, Gin, Rum, Vodka and Whisky)': 'Spirit (vodka/gin/rum/whisky)',
    'Milk, cow, fluid, reduced fat (~1%)': 'Milk, reduced fat',
    'Milk, cow, fluid, regular fat (~3.5%)': 'Milk, full fat',
    'Milk, cow, fluid, skim (~0.15% fat)': 'Milk, skim',
    'Milk, cow, fluid, lactose free, reduced fat (~1%)': 'Milk, lactose free, reduced fat',
    'Milk, cow, fluid, lactose free, regular fat (~3.5%)': 'Milk, lactose free, full fat',
    'Milk, cow, canned, evaporated, regular': 'Milk, evaporated',
    'Milk, cow, canned, evaporated, reduced fat (~2%)': 'Milk, evaporated, reduced fat',
    'Milk, cow, canned, sweetened, condensed, regular': 'Condensed milk, sweetened',
    'Milk, cow, fluid, flavoured, chocolate, reduced fat': 'Chocolate milk, reduced fat',
    'Milk, cow, powder, skim': 'Milk powder, skim',
    'Milk, cow, powder, regular fat': 'Milk powder, full fat',
    'Soy beverage, added sugar, unfortified': 'Soy milk, sweetened',
    'Almond beverage, added sugar, unfortified': 'Almond milk, sweetened',
    'Almond beverage, no added sugar, added Ca': 'Almond milk, unsweetened, with calcium',
    # ── MISC ──────────────────────────────────────────────────────────────────
    'Psyllium, husks': 'Psyllium husks',
    'Seaweed, dried': 'Seaweed, dried',
    'Wattle seed (acacia), ground': 'Wattle seed, ground',
    'Textured vegetable protein/soy granules': 'TVP / soy mince, dry',
    'Cocoa powder, plain': 'Cocoa powder',
    'Chocolate, dark, >70% cocoa solids': 'Dark chocolate, >70%',
    'Chocolate, dark, regular': 'Dark chocolate',
    'Chocolate, milk, regular': 'Milk chocolate',
    'Chocolate, white': 'White chocolate',
    'Bar, muesli, plain or with dried fruit': 'Muesli bar',
    'Bar, muesli, plain or with dried fruit, chocolate-coated': 'Muesli bar, choc-coated',
    'Bar, muesli, plain or with dried fruit, yoghurt-coated': 'Muesli bar, yoghurt-coated',
    'Bar, muesli, with nuts': 'Muesli bar, with nuts',
    'Bar, snack, fruit filled, baked': 'Snack bar, fruit filled',
    'Bar, snack, oat based, baked': 'Snack bar, oat based',
    'Bar, snack, with >35% nuts, added protein': 'Protein bar, nut based',
    'Bar, snack, with >55% nuts': 'Nut bar',
}


def main():
    print("Connecting to database...")
    conn = mysql.connector.connect(**DB_PARAMS)
    cursor = conn.cursor()

    # Get all current foods
    cursor.execute("SELECT id, name, calories, protein, carbs, fiber, fat, servingUnit, servingGrams FROM nutrition_foods ORDER BY id")
    foods = cursor.fetchall()
    print(f"Current food count: {len(foods)}")

    # Build the cleaned list
    kept = []
    removed_count = 0
    renamed_count = 0
    seen_simplified = {}  # simplified_name → True (dedup)

    for row in foods:
        food_id, name, calories, protein, carbs, fiber, fat, serving_unit, serving_grams = row

        # Check if this name should be removed
        if name in REMOVE_EXACT:
            removed_count += 1
            continue

        # Apply name mapping
        simplified = NAME_MAP.get(name, name)
        if simplified != name:
            renamed_count += 1

        # Deduplicate: if we've already kept a food with this simplified name, skip
        if simplified in seen_simplified:
            removed_count += 1
            continue

        seen_simplified[simplified] = True
        kept.append((simplified, calories, protein, carbs, fiber, fat, serving_unit, serving_grams))

    print(f"Removed: {removed_count}")
    print(f"Renamed: {renamed_count}")
    print(f"Keeping: {len(kept)}")

    # Clear and re-insert
    cursor.execute("DELETE FROM food_servings")
    cursor.execute("DELETE FROM nutrition_foods")
    conn.commit()
    print("Cleared nutrition_foods and food_servings.")

    insert_sql = """
        INSERT INTO nutrition_foods (name, calories, protein, carbs, fiber, fat, servingUnit, servingGrams)
        VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
    """
    batch_size = 200
    for i in range(0, len(kept), batch_size):
        cursor.executemany(insert_sql, kept[i:i+batch_size])
        conn.commit()

    cursor.execute("SELECT COUNT(*) FROM nutrition_foods")
    final_count = cursor.fetchone()[0]
    print(f"Final food count: {final_count}")

    # Show sample
    cursor.execute("SELECT name FROM nutrition_foods ORDER BY name LIMIT 30")
    print("\nSample (first 30 alphabetically):")
    for r in cursor.fetchall():
        print(f"  {r[0]}")

    cursor.close()
    conn.close()
    print("\nDone!")


if __name__ == '__main__':
    main()
